/* ============================================================
   SaSpark — Seed Data
   Mock dataset for the demo. In production this would come from
   an API + database (startups, funders, contributions, comments).
   ============================================================ */

const CATEGORIES = [
  { id: 'crime-safety', name: 'Crime & Safety',    iconName: 'shield'      },
  { id: 'women',        name: "Women's Safety",    iconName: 'heart'       },
  { id: 'edu',          name: 'Education',         iconName: 'book'        },
  { id: 'health',       name: 'Health & Wellness', iconName: 'activity'    },
  { id: 'fintech',      name: 'Fintech',           iconName: 'credit-card' },
  { id: 'climate',      name: 'Climate',           iconName: 'leaf'        },
  { id: 'jobs',         name: 'Jobs & Skills',     iconName: 'briefcase'   },
  { id: 'food',         name: 'Food Security',     iconName: 'wheat'       },
  { id: 'housing',      name: 'Housing',           iconName: 'home'        },
  { id: 'energy',       name: 'Energy',            iconName: 'zap'         },
  { id: 'other',        name: 'Other',             iconName: 'sparkles'    },
];

/* ─── Cover photography ─────────────────────────────────────
   Picsum (royalty-free, no API key, loads reliably) seeded by
   startup slug so each campaign gets a consistent image.
   Swap these URLs for branded campaign photography in production.
   ─────────────────────────────────────────────────────────── */
const coverFor = (slug) => `https://picsum.photos/seed/saspark-${slug}/1200/600`;

const STARTUPS = [
  {
    id: 's01',
    slug: 'safe-route',
    name: 'SafeRoute SA',
    tagline: 'AI-powered walking routes that steer you away from high-crime hotspots in real-time.',
    emoji: '🛡️',
    category: 'crime-safety',
    location: 'Johannesburg',
    founder: 'Thabo Mokoena',
    verified: true,
    fundingGoal: 850000,
    amountRaised: 612400,
    fundersCount: 1842,
    daysLeft: 22,
    views: 28430,
    trending: 98,
    createdAt: '2026-04-12',
    problem: 'Over 21,000 contact crimes are reported every month in South Africa. Pedestrians — especially after dark — have no reliable way to know which streets are safe to walk in the next 30 minutes. Existing maps treat all roads as equal. They don\'t.',
    solution: 'SafeRoute fuses live SAPS crime data, community reports, street-light status from municipalities, and real-time foot-traffic into a dynamic safety score for every street in every city. The app reroutes you on the fly when a new incident is reported within 500m of your path.',
    plan: 'Phase 1 (R250k): Pilot the Joburg CBD heatmap with 50,000 free users; ingest live SAPS feed.\nPhase 2 (R350k): Add Cape Town and Durban; build community-verification layer (Waze for safety).\nPhase 3 (R250k): Launch enterprise tier for delivery drivers, taxis, and tourism operators.',
    market: '14M urban smartphone users in SA. Initial TAM at R49/mo for premium = R8.2bn. Enterprise tier (delivery, ride-hail) adds R600m+.',
    team: [
      { name: 'Thabo Mokoena',  role: 'CEO — ex-Google Maps engineer',  initials: 'TM' },
      { name: 'Naledi Pillay',  role: 'CTO — ex-Uber safety team',      initials: 'NP' },
      { name: 'Andre Botha',    role: 'Head of Data — SAPS partnership',initials: 'AB' },
    ],
    documents: ['CIPC Registration', 'Tax Clearance', 'POPIA Compliance', 'SAPS Data MoU'],
    updates: [
      { date: '2026-05-28', title: 'Pilot live in Sandton CBD', body: 'Onboarded 4,200 users in 72 hours. Avg route delta: +6 minutes, -41% reported incidents on path.' },
      { date: '2026-05-14', title: 'SAPS data feed signed', body: 'We can now ingest hourly incident reports from 14 stations across Gauteng.' },
    ],
  },
  {
    id: 's02',
    slug: 'sister-shield',
    name: 'SisterShield',
    tagline: 'A silent panic button hidden inside everyday apps — built for women in danger of GBV.',
    emoji: '💜',
    category: 'women',
    location: 'Cape Town',
    founder: 'Lerato Khumalo',
    verified: true,
    fundingGoal: 480000,
    amountRaised: 466200,
    fundersCount: 3104,
    daysLeft: 4,
    views: 51200,
    trending: 99,
    createdAt: '2026-03-02',
    problem: 'A woman is killed every three hours in South Africa. Most cannot reach a phone in time, and abusers monitor their devices. Traditional panic buttons are visible, deletable, and easy to disable.',
    solution: 'SisterShield is an invisible SDK that any everyday app (calculator, weather, recipe apps) can integrate. A 5-tap sequence on the app icon triggers a silent alert with GPS, audio recording, and live location streaming to up to 5 trusted contacts and the nearest registered response unit.',
    plan: 'R180k: Finalise SDK and pass 3rd-party security audit.\nR200k: Partner with 10 SA app publishers (target: 8M cumulative installs).\nR100k: Build the 24/7 response-coordinator dashboard with TEARS Foundation.',
    market: '30M+ female smartphone users across SA + SADC. Free for end users; revenue from app publishers (R0.05/install/year) and enterprise (insurance, security firms).',
    team: [
      { name: 'Lerato Khumalo', role: 'CEO — survivor advocate & ex-Discovery engineer', initials: 'LK' },
      { name: 'Dr. Priya Naidoo', role: 'Chief Safety Officer — clinical psychologist',   initials: 'PN' },
      { name: 'Sipho Dlamini',  role: 'Head of Engineering — security specialist',         initials: 'SD' },
    ],
    documents: ['CIPC Registration', 'POPIA Compliance', 'Third-Party Security Audit', 'TEARS Foundation Partnership'],
    updates: [
      { date: '2026-05-30', title: '97% of goal reached', body: 'Thank you — we will close funding by Friday and start the security audit Monday.' },
      { date: '2026-05-22', title: 'TEARS Foundation joins as response partner', body: '24/7 coordinator dashboard will route alerts to the closest of 38 TEARS-trained centres nationwide.' },
    ],
  },
  {
    id: 's03',
    slug: 'mzansi-tutor',
    name: 'Mzansi Tutor',
    tagline: 'Free WhatsApp-based maths tutoring for matric learners in any of 11 SA languages.',
    emoji: '📚',
    category: 'edu',
    location: 'Durban',
    founder: 'Sibongile Zulu',
    verified: true,
    fundingGoal: 320000,
    amountRaised: 184700,
    fundersCount: 921,
    daysLeft: 31,
    views: 18900,
    trending: 87,
    createdAt: '2026-04-20',
    problem: 'Only 55% of South African learners pass matric maths. Private tutoring costs R250-R500/hour — out of reach for 80% of families. Most learners only have WhatsApp, not high-bandwidth video.',
    solution: 'A trained AI tutor that lives inside WhatsApp. Learners snap a photo of a maths problem; it returns a step-by-step solution + voice note explanation in their home language. Vetted human tutors review tricky questions within 4 hours.',
    plan: 'R120k: Train and benchmark the local-language tutor model (Sotho, Zulu, Xhosa first).\nR140k: Onboard 200 vetted university-student tutors for human escalation.\nR60k: Provincial DBE pilot partnership with 30 schools in KZN.',
    market: '900,000 matric learners per year. Sustainable on R49/mo premium tier for parents who want detailed progress reports; free core service forever.',
    team: [
      { name: 'Sibongile Zulu', role: 'CEO — former DBE curriculum advisor', initials: 'SZ' },
      { name: 'Karabo Sithole', role: 'Head of Pedagogy',                    initials: 'KS' },
    ],
    documents: ['CIPC Registration', 'NPO Status', 'DBE Pilot Memorandum'],
    updates: [
      { date: '2026-05-25', title: '5,000 learners onboarded in May', body: 'Average improvement of +14% on practice tests after 6 weeks.' },
    ],
  },
  {
    id: 's04',
    slug: 'pulse-clinic',
    name: 'Pulse Clinic',
    tagline: 'Telehealth GP consultations for R59 — covered by most medical aids and accessible from a feature phone.',
    emoji: '🩺',
    category: 'health',
    location: 'Pretoria',
    founder: 'Dr. Mandla Khoza',
    verified: true,
    fundingGoal: 1200000,
    amountRaised: 738000,
    fundersCount: 2105,
    daysLeft: 18,
    views: 33200,
    trending: 92,
    createdAt: '2026-03-18',
    problem: 'Average wait at a public clinic is 4.5 hours. 18M South Africans live further than 5km from any clinic. Telehealth services exist but require apps, smartphones, and data — excluding the people who need them most.',
    solution: 'Dial *120*PULSE# from any phone (free of charge, USSD), get connected to a registered HPCSA doctor within 6 minutes. Prescriptions delivered to a local participating pharmacy. R59 per consult, or covered by all major medical aids.',
    plan: 'R450k: Pharmacy network (target: 1,400 nationwide).\nR500k: Recruit and onboard 180 doctors for after-hours rotations.\nR250k: USSD-shortcode infrastructure and SLA with MTN/Vodacom.',
    market: '60M South Africans, 89% of whom own a phone capable of USSD. Average 2 GP visits/year = TAM of R7bn.',
    team: [
      { name: 'Dr. Mandla Khoza', role: 'CEO — GP, ex-NHI advisory panel', initials: 'MK' },
      { name: 'Alex Pretorius',   role: 'CTO — telco infrastructure',       initials: 'AP' },
      { name: 'Dr. Yolanda Maseko',role: 'Medical Director',                 initials: 'YM' },
    ],
    documents: ['CIPC Registration', 'HPCSA Practice Registration', 'POPIA Compliance', 'BHF Medical Aid Tariff Certificate'],
    updates: [
      { date: '2026-05-29', title: 'Discovery Health onboarded', body: 'Members can now claim Pulse consults at 100% on Classic and above.' },
    ],
  },
  {
    id: 's05',
    slug: 'stokvest',
    name: 'StokVest',
    tagline: 'Turn your stokvel into an investment club — track contributions, vote on investments, payout via instant EFT.',
    emoji: '💳',
    category: 'fintech',
    location: 'Johannesburg',
    founder: 'Bongani Maseko',
    verified: true,
    fundingGoal: 600000,
    amountRaised: 392000,
    fundersCount: 1234,
    daysLeft: 26,
    views: 22100,
    trending: 89,
    createdAt: '2026-04-05',
    problem: 'Stokvels hold R49 billion in savings across SA — almost all of it in low-yield bank accounts or under mattresses. Members lose money to fraud, disputes, and missed contributions. There\'s no software built for how stokvels actually work.',
    solution: 'StokVest is a stokvel-first app: members contribute via FNB instant pay, treasurers see live cash position, the group can vote (anonymously or openly) on whether to put excess into a money market fund or unit trust. PASA-licensed, fully audited monthly statements.',
    plan: 'R220k: PASA accreditation and Easy Equities partnership.\nR280k: Vernacular-language onboarding (Zulu, Xhosa, Sotho).\nR100k: Marketing — target 8,000 stokvels in year one.',
    market: '820,000 active stokvels in SA, avg 12 members. Target: R10/member/month premium tier on 5% of market = R6m ARR.',
    team: [
      { name: 'Bongani Maseko',   role: 'CEO — ex-FNB digital products',   initials: 'BM' },
      { name: 'Kefiloe Tau',      role: 'COO — chartered accountant',       initials: 'KT' },
    ],
    documents: ['CIPC Registration', 'PASA Pre-Authorisation', 'FSCA Engagement', 'POPIA Compliance'],
    updates: [
      { date: '2026-05-20', title: '120 stokvels in private beta', body: 'Average monthly contributions tracked: R4,200 per group. Zero disputed transactions in 6 weeks.' },
    ],
  },
  {
    id: 's06',
    slug: 'green-spark',
    name: 'GreenSpark',
    tagline: 'Rent-to-own solar kits for township households — installation in 2 hours, paid off in 18 months.',
    emoji: '☀️',
    category: 'energy',
    location: 'Soweto',
    founder: 'Nomvula Mthembu',
    verified: true,
    fundingGoal: 1500000,
    amountRaised: 1142000,
    fundersCount: 1876,
    daysLeft: 11,
    views: 41200,
    trending: 95,
    createdAt: '2026-03-30',
    problem: 'Loadshedding costs the SA economy R900m a day. Township households can\'t afford R40,000 inverter setups. They burn paraffin, candles, and use car batteries — leading to fires and CO poisoning.',
    solution: 'A 400W solar + battery kit that powers lights, phones, a TV, and a fridge through Stage 6 loadshedding. R299/month for 18 months, then you own it. Installed in 2 hours by trained community technicians. No deposit, no credit check.',
    plan: 'R600k: Bulk import 1,200 kits from vetted Tier-1 suppliers.\nR500k: Train and certify 40 community installers (priority: youth from the same neighbourhoods).\nR400k: Working capital for the 18-month payment cycle.',
    market: '4.2M households without reliable power. At 10% market capture: R150m ARR + asset book.',
    team: [
      { name: 'Nomvula Mthembu', role: 'CEO — ex-Eskom renewables lead', initials: 'NM' },
      { name: 'Riaan van Wyk',   role: 'Head of Installation — electrician', initials: 'RW' },
    ],
    documents: ['CIPC Registration', 'NRCS Solar Certification', 'NCR Registration', 'B-BBEE Level 1'],
    updates: [
      { date: '2026-05-26', title: '300 kits installed in Soweto pilot', body: 'Zero defects. Average household saves R280/month on paraffin & candles — covering most of the kit payment.' },
    ],
  },
  {
    id: 's07',
    slug: 'food-bridge',
    name: 'FoodBridge',
    tagline: 'Connecting supermarket surplus to community kitchens before it gets thrown out.',
    emoji: '🍞',
    category: 'food',
    location: 'Cape Town',
    founder: 'Aisha Patel',
    verified: true,
    fundingGoal: 420000,
    amountRaised: 268000,
    fundersCount: 814,
    daysLeft: 24,
    views: 14200,
    trending: 84,
    createdAt: '2026-04-15',
    problem: 'SA supermarkets throw away 10 million tonnes of perfectly good food every year. Meanwhile, 23% of South Africans go to bed hungry. Existing logistics make donation harder than dumping.',
    solution: 'A retailer-facing tablet app: a store manager taps "donate" on items near sell-by; the nearest of 280 community kitchens gets a notification; our refrigerated bakkie collects within 90 minutes. Food safety certified end-to-end.',
    plan: 'R200k: Fleet of 4 refrigerated bakkies for the Western Cape pilot.\nR150k: SACSI food-safety certification & cold-chain training.\nR70k: Onboard the next 60 retailers (have LOIs from Pick n Pay and Woolworths).',
    market: '4,800 supermarkets nationally. Free for kitchens; retailers pay R2,500/store/month for the donation receipt & ESG dashboard.',
    team: [
      { name: 'Aisha Patel',     role: 'CEO — ex-Ladles of Love operations', initials: 'AP' },
      { name: 'Themba Ndlovu',   role: 'Head of Logistics — ex-DSV',         initials: 'TN' },
    ],
    documents: ['CIPC Registration', 'NPC Status', 'SACSI Food Safety Cert', 'PnP Pilot LOI'],
    updates: [
      { date: '2026-05-18', title: '12 stores live, 8,400 meals/week', body: 'Zero spoilage, zero rejected loads. Adding the next 8 PnP stores in June.' },
    ],
  },
  {
    id: 's08',
    slug: 'kasi-jobs',
    name: 'Kasi Jobs',
    tagline: 'WhatsApp-only job board for entry-level work near you. No CV needed.',
    emoji: '💼',
    category: 'jobs',
    location: 'Johannesburg',
    founder: 'Lwazi Mbeki',
    verified: false,
    fundingGoal: 280000,
    amountRaised: 71400,
    fundersCount: 312,
    daysLeft: 38,
    views: 9400,
    trending: 71,
    createdAt: '2026-05-02',
    problem: 'Youth unemployment is at 60%. Job boards expect CVs, online accounts, and email — barriers that exclude the people who need work most.',
    solution: 'Send a WhatsApp to our number. Tell us where you live and what you can do (in voice or text, any language). We match you to verified employers within 5km and book your interview. No CV, no fee, ever.',
    plan: 'R120k: Match-quality ML model + 6-month operating costs.\nR100k: Verify the first 500 employers (KFC, Spar, McDonald\'s, Builders Warehouse in talks).\nR60k: Whatsapp Business API & support team.',
    market: '7.9M unemployed youth. Free for jobseekers; employers pay R150 per successful hire (3-month guarantee).',
    team: [
      { name: 'Lwazi Mbeki', role: 'CEO — ex-Harambee Youth Employment', initials: 'LM' },
    ],
    documents: ['CIPC Registration'],
    updates: [
      { date: '2026-05-15', title: 'Beta opens to Soweto + Tembisa', body: '210 jobseekers signed up in week one. 28 placed.' },
    ],
  },
  {
    id: 's09',
    slug: 'guardian-eyes',
    name: 'Guardian Eyes',
    tagline: 'Crowd-funded community CCTV: live, monitored, AI-flagged — without the security company markup.',
    emoji: '📹',
    category: 'crime-safety',
    location: 'Pretoria',
    founder: 'Pieter van der Merwe',
    verified: true,
    fundingGoal: 650000,
    amountRaised: 382000,
    fundersCount: 1102,
    daysLeft: 19,
    views: 24800,
    trending: 88,
    createdAt: '2026-04-08',
    problem: 'Private security costs R900-R1500/month per home. The average street has 30 homes. That\'s R30,000+ a month going to four security companies — duplicating the same patrol. Camera surveillance exists but is unaffordable and unmonitored at night.',
    solution: 'A community pools R250/month. We install 8-12 AI cameras at every entry to the suburb. Video is monitored 24/7 by a remote control room. AI flags loitering and licence plates of stolen vehicles. Alerts go directly to SAPS + responders.',
    plan: 'R350k: Pilot kit (12 cameras, NVR, fibre uplink) for 2 suburbs.\nR200k: Build the 24/7 monitoring centre.\nR100k: PSIRA security operator licensing.',
    market: '12,000 suburbs / townships in SA. Avg margin R45/home/month: R1.6bn potential ARR.',
    team: [
      { name: 'Pieter van der Merwe', role: 'CEO — ex-Fidelity ADT', initials: 'PvdM' },
      { name: 'Thabiso Phiri',         role: 'CTO — ML/computer vision', initials: 'TP' },
    ],
    documents: ['CIPC Registration', 'PSIRA Pre-Application', 'POPIA Compliance'],
    updates: [
      { date: '2026-05-12', title: 'Garsfontein Phase 1 live', body: '11 cameras up. 4 vehicle break-ins prevented in first 14 nights — alerts triggered armed response in < 90 seconds.' },
    ],
  },
  {
    id: 's10',
    slug: 'rent-buddy',
    name: 'RentBuddy',
    tagline: 'Find a verified room or flat-share in 5 minutes — without the agent fee.',
    emoji: '🏠',
    category: 'housing',
    location: 'Cape Town',
    founder: 'Yasmin Davids',
    verified: false,
    fundingGoal: 380000,
    amountRaised: 88200,
    fundersCount: 408,
    daysLeft: 33,
    views: 11200,
    trending: 76,
    createdAt: '2026-04-28',
    problem: 'Renting in SA cities is a scam minefield. Fake landlords on Gumtree, R5,000 "admin fees", deposits that vanish. Students and first-jobbers are hit hardest.',
    solution: 'Every landlord on RentBuddy is identity-verified, property-deed-checked, and deposit-protected via a regulated trust account. Tenants pay R0 to use us; we earn a small fee from landlords on lease signing.',
    plan: 'R150k: Build the deed-verification API + escrow integration.\nR130k: Trust account audit & FSCA engagement.\nR100k: Launch marketing across UCT, UJ, Wits campuses.',
    market: '1.8M urban rentals annually in SA. R250 per signing × 5% market share = R22.5m ARR.',
    team: [
      { name: 'Yasmin Davids',  role: 'CEO — ex-Property24',         initials: 'YD' },
      { name: 'Sandile Ngubo',  role: 'Head of Engineering',          initials: 'SN' },
    ],
    documents: ['CIPC Registration', 'FSCA Engagement'],
    updates: [],
  },
  {
    id: 's11',
    slug: 'open-clinic',
    name: 'OpenClinic',
    tagline: 'Health records in your pocket — across every public and private facility in SA.',
    emoji: '📋',
    category: 'health',
    location: 'Johannesburg',
    founder: 'Dr. Reshma Govender',
    verified: true,
    fundingGoal: 780000,
    amountRaised: 412000,
    fundersCount: 893,
    daysLeft: 27,
    views: 18900,
    trending: 82,
    createdAt: '2026-04-10',
    problem: 'Switch from a public clinic to private, or move provinces — and your medical history is gone. Doctors order duplicate tests, miss allergies, and prescribe drugs that conflict with what you were already on.',
    solution: 'A standards-based personal health record (FHIR). You own it. Any doctor scans a QR code and sees only what you allow — last visit, allergies, current meds, scans. Works offline, syncs when connected.',
    plan: 'R350k: HL7 FHIR-compliant backend & POPIA-compliant architecture.\nR280k: 12-clinic Gauteng pilot (mix of public + private).\nR150k: Apple Wallet / Google Wallet integration.',
    market: '60M South Africans. Free for patients; clinics pay R49/doctor/month for the read/write integration.',
    team: [
      { name: 'Dr. Reshma Govender', role: 'CEO — clinical informaticist, MBBCh + MSc HI', initials: 'RG' },
      { name: 'Marcus Stuurman',     role: 'CTO — ex-Discovery Health systems',              initials: 'MS' },
    ],
    documents: ['CIPC Registration', 'POPIA Compliance', 'HPCSA Advisory Letter'],
    updates: [
      { date: '2026-05-22', title: 'Tembisa Hospital pilot signed', body: '38,000 monthly OPD patients to be issued OpenClinic IDs over the next 90 days.' },
    ],
  },
  {
    id: 's12',
    slug: 'crop-cast',
    name: 'CropCast',
    tagline: 'Pinpoint weather + soil insights for small farmers, sent by SMS at 5am every day.',
    emoji: '🌾',
    category: 'climate',
    location: 'Limpopo',
    founder: 'Tshepo Maluleke',
    verified: true,
    fundingGoal: 340000,
    amountRaised: 198000,
    fundersCount: 644,
    daysLeft: 21,
    views: 12400,
    trending: 80,
    createdAt: '2026-04-22',
    problem: 'Small-scale farmers (2.3M of them) feed a third of SA but get the same generic weather forecast as someone in a city — missing a 6-hour window of frost or a 2-day dry spell that can wreck a crop.',
    solution: 'Satellite soil-moisture + hyperlocal weather modelling per 100m × 100m grid square. Daily SMS in your language: "Plant tomorrow. Skip irrigating Tuesday. Frost risk Thursday morning — cover seedlings."',
    plan: 'R140k: Satellite data partnership (ESA + Sentinel API).\nR130k: Field validation: 200 farmers across 3 provinces.\nR70k: Sub-Saharan ML model improvements vs generic global forecasts.',
    market: '2.3M smallholder farmers in SA + 70M in SADC. R20/month per farmer subscription.',
    team: [
      { name: 'Tshepo Maluleke',    role: 'CEO — agronomist, 3rd-gen farmer', initials: 'TM' },
      { name: 'Dr. Ingrid Hartwig', role: 'Chief Scientist — climate modeller', initials: 'IH' },
    ],
    documents: ['CIPC Registration', 'AgriSA Member'],
    updates: [
      { date: '2026-05-08', title: '420 farmers active across Limpopo', body: 'Avg yield improvement: 18% vs prior season at matched sites. Subscription retention: 94%.' },
    ],
  },
  {
    id: 's13',
    slug: 'code-kids',
    name: 'CodeKids',
    tagline: 'Coding bootcamps that pay students to learn — funded by an upfront-free, income-share model.',
    emoji: '💻',
    category: 'edu',
    location: 'Cape Town',
    founder: 'Sasha Williams',
    verified: false,
    fundingGoal: 950000,
    amountRaised: 287000,
    fundersCount: 421,
    daysLeft: 35,
    views: 9800,
    trending: 73,
    createdAt: '2026-05-01',
    problem: 'A 12-month bootcamp costs R85k — out of reach for the youth most likely to be unemployed. Free bootcamps run out of money and quality drops fast.',
    solution: 'You pay R0 to enrol. You earn a R3,500/month stipend during the 9-month bootcamp. When you land a R20k+/month tech job, you pay back 12% of salary for 30 months. Outcomes: 78% placement, average R28k starting salary.',
    plan: 'R500k: Stipend pool for the next cohort of 40 learners.\nR300k: Curriculum + senior instructors.\nR150k: Employer partnership team — 60 companies already in the network.',
    market: '60% youth unemployment. Each R85k learner generates ~R100k repayments + R250k tax base for the country.',
    team: [
      { name: 'Sasha Williams', role: 'CEO — ex-WeThinkCode_', initials: 'SW' },
    ],
    documents: ['CIPC Registration', 'QCTO Skills Provider — In Review'],
    updates: [],
  },
  {
    id: 's14',
    slug: 'cleanwater-zw',
    name: 'CleanFlow',
    tagline: 'Affordable household water filters certified to remove bacteria, lead, and microplastics.',
    emoji: '💧',
    category: 'health',
    location: 'Pretoria',
    founder: 'Anele Nkosi',
    verified: true,
    fundingGoal: 520000,
    amountRaised: 188400,
    fundersCount: 519,
    daysLeft: 29,
    views: 11800,
    trending: 77,
    createdAt: '2026-04-18',
    problem: 'Roughly 3 million South Africans don\'t have reliable access to safe drinking water. Most "filter jugs" remove taste but not pathogens. Lab-grade filters cost R3,000+.',
    solution: 'A locally-manufactured ceramic-carbon filter, certified by SABS and the SA Water Research Commission, that retails for R249 and lasts 12 months at 6L/day. Sold direct + via Shoprite Usave.',
    plan: 'R220k: Tooling and first production run of 4,000 units.\nR200k: SABS / WRC certification (final phase).\nR100k: Distribution into 60 Usave stores.',
    market: '4M underserved households + 1M premium households tired of bottled water = R600m TAM at unit price.',
    team: [
      { name: 'Anele Nkosi',       role: 'CEO — chemical engineer',  initials: 'AN' },
      { name: 'Dr. Boitumelo Lefa', role: 'Chief Scientist — WRC',    initials: 'BL' },
    ],
    documents: ['CIPC Registration', 'SABS Pre-Certification', 'WRC Engagement', 'NRCS Manufacturing'],
    updates: [
      { date: '2026-04-30', title: 'WRC stage-1 testing passed', body: 'Filter removed 99.997% of E.coli and 94% of lead at 6L/day rate. Stage-2 (lifecycle) starts in June.' },
    ],
  },
  {
    id: 's15',
    slug: 'safe-share',
    name: 'SafeShare',
    tagline: 'Anonymous app for reporting GBV, helping survivors find shelters, lawyers, and trauma counsellors nearby.',
    emoji: '🤝',
    category: 'women',
    location: 'Johannesburg',
    founder: 'Refilwe Mahlangu',
    verified: true,
    fundingGoal: 290000,
    amountRaised: 215000,
    fundersCount: 1421,
    daysLeft: 14,
    views: 19200,
    trending: 91,
    createdAt: '2026-04-25',
    problem: 'Most GBV survivors don\'t know which shelter has beds, which lawyer takes pro bono cases, or which counsellor speaks their language. Existing directories are out of date and require Internet.',
    solution: 'A free app + USSD service. Real-time bed availability at 280+ shelters. Pro-bono lawyer matching via the Law Society. Telehealth counselling sessions. Fully anonymous. Built with input from 60 survivor advocates.',
    plan: 'R130k: Live integration with shelter bed-management systems.\nR100k: Pro-bono lawyer onboarding.\nR60k: USSD code for the 30% of survivors without smartphones.',
    market: 'Free for survivors forever. Funded by foundations + ESG corporate sponsors (already secured: Sanlam Foundation, Old Mutual Rewards).',
    team: [
      { name: 'Refilwe Mahlangu', role: 'Founder — survivor + advocate',     initials: 'RM' },
      { name: 'Adv. Lisa Stein',   role: 'Legal Lead — pro bono coordinator', initials: 'LS' },
    ],
    documents: ['CIPC Registration', 'NPO Status', 'TEARS Partnership', 'Law Society MoU'],
    updates: [
      { date: '2026-05-21', title: '6,200 referrals in pilot', body: 'Live in Gauteng + Western Cape. 96% of users were connected to a service within 4 hours.' },
    ],
  },
  {
    id: 's16',
    slug: 'cred-score-sa',
    name: 'CredScoreSA',
    tagline: 'Build a credit score from rent, airtime, and stokvel payments — for the 30M unbanked & thin-file South Africans.',
    emoji: '📊',
    category: 'fintech',
    location: 'Cape Town',
    founder: 'Mpho Ramaphosa',
    verified: true,
    fundingGoal: 720000,
    amountRaised: 308000,
    fundersCount: 612,
    daysLeft: 23,
    views: 16400,
    trending: 81,
    createdAt: '2026-04-14',
    problem: 'If you\'ve never had a credit card or store account, banks treat you as un-scorable. So you can\'t get a home loan, car finance, or even a R1,000 emergency loan — even if you\'ve paid R6k/month rent for ten years.',
    solution: 'An alternative-data credit score that ingests rent receipts, airtime top-ups, mobile-wallet activity, stokvel history, and Capitec / TymeBank cash flow. NCR-engaged, FSCA-compliant. Free score for consumers; lenders pay per query.',
    plan: 'R350k: Build & validate the scorecard against bureau outcomes.\nR250k: NCR Tier-2 credit bureau application.\nR120k: First 3 lender integrations.',
    market: '30M un/under-scored adults. SA alt-credit market projected at R8bn by 2028.',
    team: [
      { name: 'Mpho Ramaphosa', role: 'CEO — ex-Experian SA, data scientist', initials: 'MR' },
      { name: 'Ofentse Cele',   role: 'Head of Compliance — NCR-qualified',    initials: 'OC' },
    ],
    documents: ['CIPC Registration', 'NCR Application', 'POPIA Compliance', 'FSCA Engagement'],
    updates: [],
  },
  {
    id: 's17',
    slug: 'taxi-pulse',
    name: 'TaxiPulse',
    tagline: 'Live minibus taxi route + arrival info — the missing transit app for the 60% of South Africans who use kombis.',
    emoji: '🚐',
    category: 'jobs',
    location: 'Johannesburg',
    founder: 'Sello Kgomo',
    verified: false,
    fundingGoal: 410000,
    amountRaised: 142000,
    fundersCount: 388,
    daysLeft: 30,
    views: 10800,
    trending: 75,
    createdAt: '2026-04-26',
    problem: '16.5M people use minibus taxis daily. No map shows where any of the 200,000 routes go, what they cost, or when the next one leaves. New residents and tourists are stranded.',
    solution: 'A passenger app + driver-side ranking. Drivers tap "departing" with one button; passengers see live ETA, route, fare, and rank. Free for both — we earn from in-rank ads and route-data licensing.',
    plan: 'R180k: SANTACO partnership rollout for 12 ranks.\nR130k: Driver-side onboarding + USSD fallback.\nR100k: Passenger app marketing.',
    market: '16.5M daily users. Indirect rev: route data already requested by 4 municipalities at R200k/year each.',
    team: [
      { name: 'Sello Kgomo', role: 'CEO — ex-Uber product manager', initials: 'SK' },
    ],
    documents: ['CIPC Registration', 'SANTACO LOI'],
    updates: [
      { date: '2026-05-19', title: 'Bree Taxi Rank live', body: '4,800 daily app sessions. 38 drivers using the departing-button button.' },
    ],
  },
  {
    id: 's18',
    slug: 'eco-bin',
    name: 'EcoBin',
    tagline: 'Smart bins that pay you back for recycling — built into every Spar and Pick n Pay.',
    emoji: '♻️',
    category: 'climate',
    location: 'Durban',
    founder: 'Khanyisile Dube',
    verified: false,
    fundingGoal: 470000,
    amountRaised: 96000,
    fundersCount: 218,
    daysLeft: 41,
    views: 7200,
    trending: 68,
    createdAt: '2026-05-06',
    problem: 'SA recycles 11% of its plastic. Most informal pickers earn R30 a day. Households have no incentive to separate waste.',
    solution: 'A smart bin in every supermarket. Drop in a bottle — get airtime, electricity, or vouchers credited via QR scan. Pickers earn 4× current rates by delivering bulk to the same network.',
    plan: 'R220k: Pilot 30 smart bins across KZN Spars.\nR150k: Plastics-SA off-take agreement.\nR100k: Operational ops & maintenance.',
    market: '8,000+ store sites. 50t/store/year × R3/kg margin = R1.2m per 1,000 stores.',
    team: [
      { name: 'Khanyisile Dube', role: 'CEO — environmental engineer', initials: 'KD' },
    ],
    documents: ['CIPC Registration'],
    updates: [],
  },
  {
    id: 's19',
    slug: 'guard-zone',
    name: 'GuardZone',
    tagline: 'Geofenced panic-trigger for school perimeters — alerts when an unverified vehicle lingers near a school.',
    emoji: '🚨',
    category: 'crime-safety',
    location: 'Pretoria',
    founder: 'Lebo Ramoshaba',
    verified: true,
    fundingGoal: 380000,
    amountRaised: 244000,
    fundersCount: 707,
    daysLeft: 17,
    views: 14600,
    trending: 86,
    createdAt: '2026-04-19',
    problem: 'A child is abducted in SA every 25 minutes. Most kidnappings start within 200m of a school gate. Existing CCTV is reactive — it tells you what already happened.',
    solution: 'A pole-mounted unit installs at each school gate. AI detects vehicles that loiter > 7 minutes without a recognised school-parent number plate. Alerts go to the principal\'s phone + SAPS + a trained school monitor within 90 seconds.',
    plan: 'R180k: Pilot kit at 6 high-risk schools across Gauteng.\nR130k: Computer vision model fine-tuning for SA plates.\nR70k: School monitor training.',
    market: '30,000 schools nationwide. R500/school/month SaaS + hardware: R180m TAM.',
    team: [
      { name: 'Lebo Ramoshaba', role: 'CEO — ex-SAPS crime analyst', initials: 'LR' },
      { name: 'Vusi Mahlangu', role: 'CTO — embedded systems engineer', initials: 'VM' },
    ],
    documents: ['CIPC Registration', 'POPIA Compliance', 'DBE Engagement'],
    updates: [
      { date: '2026-05-16', title: 'Two safe interventions in pilot', body: 'GuardZone flagged a stolen vehicle outside Mamelodi Primary; SAPS recovered the car within 4 minutes of the alert.' },
    ],
  },
  {
    id: 's20',
    slug: 'cycle-up',
    name: 'CycleUp',
    tagline: 'Rent a bike for R10/day, paid by tapping your school ID. Designed for learners in places without taxi access.',
    emoji: '🚴',
    category: 'edu',
    location: 'Eastern Cape',
    founder: 'Zandile Sithole',
    verified: false,
    fundingGoal: 220000,
    amountRaised: 41000,
    fundersCount: 167,
    daysLeft: 44,
    views: 5800,
    trending: 64,
    createdAt: '2026-05-10',
    problem: '320,000 learners walk more than 5km each way to school in the Eastern Cape and KZN. They arrive exhausted, drop out earlier, and underperform.',
    solution: 'Solar-charged bicycle stations at rural schools. Learners tap their school ID, take a bike for the day, return it. Foundation-subsidised — out-of-pocket cost: R10/day or earned via classroom attendance.',
    plan: 'R110k: 2 stations + 30 bikes in pilot district.\nR70k: Solar charging & GPS theft prevention.\nR40k: Ops & maintenance.',
    market: 'Foundation-funded; long-term grant pipeline from DBE & Lotto.',
    team: [
      { name: 'Zandile Sithole', role: 'Founder — ex-teacher, M.Ed', initials: 'ZS' },
    ],
    documents: ['CIPC Registration'],
    updates: [],
  },
  {
    id: 's21',
    slug: 'mama-care',
    name: 'MamaCare',
    tagline: 'Free WhatsApp midwife support for first-time mothers — daily checkups, alerts, and red-flag screening.',
    emoji: '👶',
    category: 'health',
    location: 'Soweto',
    founder: 'Nokuthula Buthelezi',
    verified: true,
    fundingGoal: 360000,
    amountRaised: 251000,
    fundersCount: 1014,
    daysLeft: 16,
    views: 17800,
    trending: 88,
    createdAt: '2026-04-21',
    problem: 'SA\'s maternal mortality rate is 109 per 100,000 births — 5× the OECD average. Most deaths are preventable: late-detected pre-eclampsia, anaemia, or unsafe home births.',
    solution: 'Daily 60-second WhatsApp check-in: tap one of 6 emoji how-do-you-feel options. Our nurse-trained AI flags symptoms that need a clinic visit. Free, in your language. Co-built with Soweto-based Department of Health clinics.',
    plan: 'R180k: HPCSA-supervised AI triage validation.\nR120k: Translation into all 11 official languages.\nR60k: Outreach team — recruit 5,000 mothers in year one.',
    market: '1.1M births/year in SA. Free for mothers; medical aids pay R40/mother enrolled (rate already negotiated with Bonitas).',
    team: [
      { name: 'Nokuthula Buthelezi', role: 'CEO — midwife, MMed', initials: 'NB' },
      { name: 'Dr. Ahmed Patel',     role: 'Chief Medical Officer — obstetrician', initials: 'AP' },
    ],
    documents: ['CIPC Registration', 'HPCSA Practice', 'POPIA Compliance', 'NDoH Engagement'],
    updates: [
      { date: '2026-05-24', title: '2,200 mothers enrolled', body: '14 red-flag escalations led to early intervention. Zero adverse outcomes in our cohort.' },
    ],
  },
  {
    id: 's22',
    slug: 'sa-savings',
    name: 'SaSavings',
    tagline: 'A round-up debit card: every swipe rounds up to the nearest R10 and invests the change.',
    emoji: '💰',
    category: 'fintech',
    location: 'Cape Town',
    founder: 'Tlali Mahlangu',
    verified: false,
    fundingGoal: 540000,
    amountRaised: 121000,
    fundersCount: 304,
    daysLeft: 36,
    views: 9100,
    trending: 70,
    createdAt: '2026-05-04',
    problem: 'Only 6% of South Africans have meaningful savings. Most "saving" apps require thinking — and we don\'t.',
    solution: 'A debit card. Every R36.40 coffee rounds up to R40 — the R3.60 difference goes into a low-fee unit trust. No willpower needed. Withdraw any time.',
    plan: 'R220k: BIN sponsor partnership & card manufacturing.\nR200k: FSCA Cat-II license + JSE-linked fund.\nR120k: Onboarding marketing.',
    market: '30M adult cardholders. Avg R250/month invested per active user.',
    team: [
      { name: 'Tlali Mahlangu', role: 'CEO — ex-Capitec product', initials: 'TM' },
    ],
    documents: ['CIPC Registration', 'FSCA Pre-Application'],
    updates: [],
  },
  {
    id: 's23',
    slug: 'farm-loan',
    name: 'FarmLoan',
    tagline: 'Working-capital loans for small farmers — secured against your next harvest, repayable when you sell.',
    emoji: '🌽',
    category: 'food',
    location: 'Free State',
    founder: 'Boitumelo Khune',
    verified: true,
    fundingGoal: 870000,
    amountRaised: 354000,
    fundersCount: 542,
    daysLeft: 25,
    views: 13200,
    trending: 79,
    createdAt: '2026-04-13',
    problem: 'Small farmers can\'t get planting season loans because they don\'t have land title (they farm communal or rented land). Loan sharks fill the gap at 40% interest.',
    solution: 'Loans of R5,000-R80,000 backed by satellite-verified crop progress + buyer offtake agreements with Tiger Brands, Premier, Pioneer Foods. Interest: 1.5% per month. Default rate so far: 2.8%.',
    plan: 'R450k: Loan book capital.\nR250k: Satellite + farm-visit verification team.\nR170k: Tech platform & NCR licensing.',
    market: '2.3M smallholder farmers. R8bn capital gap. Even 1% market share is R80m loan book.',
    team: [
      { name: 'Boitumelo Khune', role: 'CEO — ex-Land Bank credit officer', initials: 'BK' },
      { name: 'Jaco Steyn',     role: 'Head of Risk — chartered accountant', initials: 'JS' },
    ],
    documents: ['CIPC Registration', 'NCR Registration', 'Land Bank Partnership LOI'],
    updates: [
      { date: '2026-05-11', title: '180 farmers in pilot', body: 'R6.2m loaned, R5.4m repaid + interest. Avg ROI for farmers: 320% on the season.' },
    ],
  },
  {
    id: 's24',
    slug: 'voice-help',
    name: 'VoiceHelp',
    tagline: 'Speak to government — pension claims, ID renewals, UIF — in your home language, by phone.',
    emoji: '📞',
    category: 'other',
    location: 'Pretoria',
    founder: 'Khotso Mahlobo',
    verified: false,
    fundingGoal: 460000,
    amountRaised: 113000,
    fundersCount: 287,
    daysLeft: 32,
    views: 8900,
    trending: 72,
    createdAt: '2026-04-30',
    problem: 'Government services require online forms, English literacy, and time off work. The elderly and rural poor are excluded from the services they\'re entitled to.',
    solution: 'Call our number. Speak in your home language. Our AI agent (with human escalation) starts your SASSA, Home Affairs, or UIF application, gives you a reference number, and SMSs you progress updates.',
    plan: 'R200k: Voice AI fine-tuning for 11 official languages.\nR160k: 24/7 human support team for escalations.\nR100k: Govt API partnerships (SASSA already in conversation).',
    market: 'Free service. Funded by 3-year deal with Public Service Commission + foundation grants.',
    team: [
      { name: 'Khotso Mahlobo', role: 'CEO — ex-DPSA innovation team', initials: 'KM' },
    ],
    documents: ['CIPC Registration', 'NPC Status'],
    updates: [],
  },
  {
    id: 's25',
    slug: 'spaza-pay',
    name: 'SpazaPay',
    tagline: 'Card payments + supplier credit for spaza shops, no fees on transactions under R50.',
    emoji: '🏪',
    category: 'fintech',
    location: 'Johannesburg',
    founder: 'Sandile Dube',
    verified: true,
    fundingGoal: 690000,
    amountRaised: 462000,
    fundersCount: 1024,
    daysLeft: 12,
    views: 19400,
    trending: 90,
    createdAt: '2026-04-08',
    problem: 'The 150,000 spaza shops in SA do R200bn/year in cash. Crime, change-shortages, and supplier relationships eat 30% of their margin. Existing card terminals charge fees that wipe out the profit on a R12 loaf of bread.',
    solution: 'A R299 card terminal (free for the first 12 months). No fees on transactions under R50. Built-in supplier credit: tap your terminal to reorder bread, milk, airtime — pay supplier in 7 days from card receipts.',
    plan: 'R350k: Manufacture and deploy first 2,000 terminals.\nR240k: Working capital for the supplier-credit float.\nR100k: PCI-DSS certification (final stage).',
    market: '150,000 spaza shops, avg R130k turnover/month. 3% take-rate ceiling: R5.8bn ARR.',
    team: [
      { name: 'Sandile Dube',   role: 'CEO — ex-Yoco product head', initials: 'SD' },
      { name: 'Aaliyah Khan',   role: 'CTO — payments engineer',     initials: 'AK' },
    ],
    documents: ['CIPC Registration', 'PCI-DSS — Stage 4', 'PASA Registration', 'POPIA Compliance'],
    updates: [
      { date: '2026-05-27', title: '410 spazas on the network', body: 'Avg uplift: 18% in revenue (driven by card-paying customers who used to walk past). Zero charge-backs.' },
    ],
  },
];

/* Funders — for the leaderboard */
const FUNDERS = [
  { id: 'f01', name: 'Naledi Phakathi',     totalContributed: 48500, startupsCount: 22, joined: '2026-01-15', initials: 'NP' },
  { id: 'f02', name: 'James Oosthuizen',    totalContributed: 42200, startupsCount: 18, joined: '2026-01-22', initials: 'JO' },
  { id: 'f03', name: 'Anonymous',           totalContributed: 38000, startupsCount: 12, joined: '2026-02-04', initials: '··' },
  { id: 'f04', name: 'Yusuf Patel',         totalContributed: 34800, startupsCount: 19, joined: '2026-01-30', initials: 'YP' },
  { id: 'f05', name: 'Lerato Sibanda',      totalContributed: 28900, startupsCount: 24, joined: '2026-02-10', initials: 'LS' },
  { id: 'f06', name: 'Marie van Niekerk',   totalContributed: 26100, startupsCount: 11, joined: '2026-02-18', initials: 'MV' },
  { id: 'f07', name: 'Sipho Mahlangu',      totalContributed: 24400, startupsCount: 15, joined: '2026-03-01', initials: 'SM' },
  { id: 'f08', name: 'Dr. Riaan Joubert',   totalContributed: 22000, startupsCount: 9,  joined: '2026-02-25', initials: 'RJ' },
  { id: 'f09', name: 'Anonymous',           totalContributed: 20800, startupsCount: 4,  joined: '2026-03-12', initials: '··' },
  { id: 'f10', name: 'Asanda Mokoena',      totalContributed: 18900, startupsCount: 17, joined: '2026-02-08', initials: 'AM' },
  { id: 'f11', name: 'Pumla Mthethwa',      totalContributed: 17200, startupsCount: 13, joined: '2026-03-04', initials: 'PM' },
  { id: 'f12', name: 'Ethan O\'Brien',      totalContributed: 16400, startupsCount: 8,  joined: '2026-03-18', initials: 'EO' },
  { id: 'f13', name: 'Tshegofatso Maleka',  totalContributed: 15800, startupsCount: 21, joined: '2026-02-14', initials: 'TM' },
  { id: 'f14', name: 'Sarah Williams',      totalContributed: 14600, startupsCount: 10, joined: '2026-03-22', initials: 'SW' },
  { id: 'f15', name: 'Bongani Mthembu',     totalContributed: 13900, startupsCount: 11, joined: '2026-03-08', initials: 'BM' },
  { id: 'f16', name: 'Anonymous',           totalContributed: 13100, startupsCount: 6,  joined: '2026-04-02', initials: '··' },
  { id: 'f17', name: 'Reza Cassim',         totalContributed: 12800, startupsCount: 9,  joined: '2026-03-14', initials: 'RC' },
  { id: 'f18', name: 'Bianca du Plessis',   totalContributed: 12000, startupsCount: 14, joined: '2026-03-26', initials: 'BD' },
  { id: 'f19', name: 'Kgothatso Tau',       totalContributed: 11400, startupsCount: 8,  joined: '2026-04-08', initials: 'KT' },
  { id: 'f20', name: 'Hannah Petersen',     totalContributed: 10900, startupsCount: 12, joined: '2026-03-30', initials: 'HP' },
  { id: 'f21', name: 'Lwazi Khumalo',       totalContributed: 10100, startupsCount: 6,  joined: '2026-04-12', initials: 'LK' },
  { id: 'f22', name: 'Nadia Hassan',        totalContributed: 9600,  startupsCount: 9,  joined: '2026-04-04', initials: 'NH' },
  { id: 'f23', name: 'Themba Dlamini',      totalContributed: 9200,  startupsCount: 11, joined: '2026-04-16', initials: 'TD' },
  { id: 'f24', name: 'Olivia Pretorius',    totalContributed: 8800,  startupsCount: 5,  joined: '2026-04-20', initials: 'OP' },
  { id: 'f25', name: 'Anonymous',           totalContributed: 8200,  startupsCount: 3,  joined: '2026-04-26', initials: '··' },
  { id: 'f26', name: 'Ayanda Khoza',        totalContributed: 7600,  startupsCount: 7,  joined: '2026-04-10', initials: 'AK' },
  { id: 'f27', name: 'Connor Smith',        totalContributed: 7100,  startupsCount: 4,  joined: '2026-04-28', initials: 'CS' },
  { id: 'f28', name: 'Refiloe Tau',         totalContributed: 6800,  startupsCount: 8,  joined: '2026-04-22', initials: 'RT' },
  { id: 'f29', name: 'Vusumzi Cele',        totalContributed: 6200,  startupsCount: 5,  joined: '2026-05-04', initials: 'VC' },
  { id: 'f30', name: 'Mihlali Booi',        totalContributed: 5900,  startupsCount: 6,  joined: '2026-04-30', initials: 'MB' },
  { id: 'f31', name: 'Brian Khoza',         totalContributed: 5400,  startupsCount: 3,  joined: '2026-05-10', initials: 'BK' },
  { id: 'f32', name: 'Anonymous',           totalContributed: 4900,  startupsCount: 2,  joined: '2026-05-08', initials: '··' },
  { id: 'f33', name: 'Lucy Maharaj',        totalContributed: 4400,  startupsCount: 4,  joined: '2026-05-12', initials: 'LM' },
  { id: 'f34', name: 'Phila Mokoena',       totalContributed: 4100,  startupsCount: 5,  joined: '2026-05-02', initials: 'PM' },
  { id: 'f35', name: 'Joshua Adams',        totalContributed: 3700,  startupsCount: 2,  joined: '2026-05-16', initials: 'JA' },
];

/* Sample recent contributions per startup — for the funders feed on detail page */
const RECENT_CONTRIBUTIONS = {
  's02': [
    { funder: 'Naledi P.',    amount: 5000, msg: 'My niece deserves a safer world. Thank you for building this.' },
    { funder: 'Anonymous',    amount: 2500, msg: 'Praying for every woman in danger tonight.' },
    { funder: 'James O.',     amount: 1000, msg: 'GBV must end. Funding the technology that helps.' },
    { funder: 'Lerato S.',    amount: 500,  msg: '' },
    { funder: 'Anonymous',    amount: 250,  msg: 'Every rand counts.' },
    { funder: 'Tshego M.',    amount: 100,  msg: 'In honour of every survivor I know.' },
  ],
  's01': [
    { funder: 'Yusuf P.',     amount: 3000, msg: 'I walk to work every morning. This will save lives.' },
    { funder: 'Anonymous',    amount: 1500, msg: 'Cape Town needs this too — please come down here.' },
    { funder: 'Marie v.N.',   amount: 800,  msg: '' },
    { funder: 'Sipho M.',     amount: 500,  msg: 'Smart, simple, urgent.' },
    { funder: 'Anonymous',    amount: 50,   msg: 'Wishing I could give more.' },
  ],
};

window.SASPARK = {
  CATEGORIES,
  STARTUPS,
  FUNDERS,
  RECENT_CONTRIBUTIONS,
};
